/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InvestigatorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.InsuranceInvestigatorOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ApprovalRequest;
import Business.WorkQueue.ClaimApprovalRequest;
import Business.WorkQueue.HospitalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class VerifyClaimJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerifyClaimJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    ClaimApprovalRequest request1;
    HospitalWorkRequest hrequest;
    int totalAmount;
    int claimAmount;
    boolean flag= false;

    VerifyClaimJPanel(JPanel userProcessContainer, Enterprise enterprise, ClaimApprovalRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.request1 = request;
        populateForms();
    }
    
    public void populateForms(){
        customerNameTextField.setText(request1.getCustomerName());
        sumInsuredTextField.setText(request1.getSumInsured());
        claimAmountJTextField.setText(request1.getClaimAmt());
        
        
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof InsuranceInvestigatorOrganization)
            {
                for(WorkRequest request : org.getWorkQueue().getWorkRequestList())
                {
                    if(request instanceof HospitalWorkRequest)
                    {
                            totalAmountTextField.setText(String.valueOf(((HospitalWorkRequest) request).getTotalBill()));
                            treatmentTypeHosTextField.setText(String.valueOf(((HospitalWorkRequest) request).getTreatmentType()));
                            treatmentAmountHosTextField.setText(String.valueOf(((HospitalWorkRequest) request).getTreatmentAmount()));
                            treatmentDateHosTextField.setText(String.valueOf(((HospitalWorkRequest) request).getTreatmentDate()));
                            pharmacyAmountTextField.setText(String.valueOf(((HospitalWorkRequest) request).getPharmacyAmount()));
                           totalAmount = Integer.parseInt(totalAmountTextField.getText());
                           claimAmount = Integer.parseInt(claimAmountJTextField.getText());
                           if(claimAmount > totalAmount)
                           {
                               claimstatusJLabel.setText("Fraud Claim");
                               
                           }
                           else{
                               claimstatusJLabel.setText("Genuine Claim");
                           }
                           flag = true;
                               
                    }
                }
                
            }
        }
        if(flag == false)
        {
          claimstatusJLabel.setText("Fraud Claim");
                           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyClaimJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        claimDetailsJLabel = new javax.swing.JLabel();
        hositalDetailsJLabel = new javax.swing.JLabel();
        sumInsuredJLabel = new javax.swing.JLabel();
        sumInsuredTextField = new javax.swing.JTextField();
        claimAmountJLabel = new javax.swing.JLabel();
        claimAmountJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pharmacyAmountTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        treatmentTypeHosTextField = new javax.swing.JTextField();
        treatmentDateHosTextField = new javax.swing.JTextField();
        treatmentAmountHosTextField = new javax.swing.JTextField();
        approveJButton = new javax.swing.JButton();
        denyJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        claimstatusJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verifyClaimJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verifyClaimJLabel.setText("Verify Claims");
        add(verifyClaimJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, -1, -1));

        jLabel1.setText("Customer Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 61, -1, -1));
        add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 58, 107, -1));

        claimDetailsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        claimDetailsJLabel.setText("CLAIM DETAILS");
        add(claimDetailsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 145, -1, -1));

        hositalDetailsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hositalDetailsJLabel.setText("HOSPITAL DETAILS");
        add(hositalDetailsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 145, -1, -1));

        sumInsuredJLabel.setText("Sum Insured :");
        add(sumInsuredJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 273, -1, -1));

        sumInsuredTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumInsuredTextFieldActionPerformed(evt);
            }
        });
        sumInsuredTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sumInsuredTextFieldKeyTyped(evt);
            }
        });
        add(sumInsuredTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 270, 139, -1));

        claimAmountJLabel.setText("Claim Amount :");
        add(claimAmountJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 311, -1, -1));

        claimAmountJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claimAmountJTextFieldKeyTyped(evt);
            }
        });
        add(claimAmountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 308, 139, -1));

        jLabel5.setText("Pharmacy Amount:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 311, -1, -1));
        add(pharmacyAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 308, 75, -1));

        jLabel6.setText("Treatment Type:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 194, -1, -1));

        jLabel7.setText("Treatment Date:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 235, -1, -1));

        jLabel8.setText("Treatment Amount:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 273, -1, -1));
        add(treatmentTypeHosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 191, 75, -1));
        add(treatmentDateHosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 232, 75, -1));
        add(treatmentAmountHosTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 270, 75, -1));

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });
        add(approveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 86, 30));

        denyJButton.setText("Deny");
        denyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyJButtonActionPerformed(evt);
            }
        });
        add(denyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 82, 35));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        add(claimstatusJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 370, 110, 30));

        jLabel9.setText("Total Amount");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));
        add(totalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 75, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sumInsuredTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumInsuredTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumInsuredTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        request1.setMessage("Approved");
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void denyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyJButtonActionPerformed
        // TODO add your handling code here:
        request1.setMessage("Denied");
    }//GEN-LAST:event_denyJButtonActionPerformed

    private void sumInsuredTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumInsuredTextFieldKeyTyped
        // TODO add your handling code here:
        char enteredText = evt.getKeyChar();
       if(!(Character.isDigit(enteredText))|| enteredText == KeyEvent.VK_BACK_SPACE || enteredText == KeyEvent.VK_DELETE)
       {
           evt.consume();
       }
    }//GEN-LAST:event_sumInsuredTextFieldKeyTyped

    private void claimAmountJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claimAmountJTextFieldKeyTyped
        // TODO add your handling code here:char enteredText = evt.getKeyChar();
        char enteredText = evt.getKeyChar();
       if(!(Character.isDigit(enteredText))|| enteredText == KeyEvent.VK_BACK_SPACE || enteredText == KeyEvent.VK_DELETE)
       {
           evt.consume();
       }
    }//GEN-LAST:event_claimAmountJTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel claimAmountJLabel;
    private javax.swing.JTextField claimAmountJTextField;
    private javax.swing.JLabel claimDetailsJLabel;
    private javax.swing.JLabel claimstatusJLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton denyJButton;
    private javax.swing.JLabel hositalDetailsJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pharmacyAmountTextField;
    private javax.swing.JLabel sumInsuredJLabel;
    private javax.swing.JTextField sumInsuredTextField;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JTextField treatmentAmountHosTextField;
    private javax.swing.JTextField treatmentDateHosTextField;
    private javax.swing.JTextField treatmentTypeHosTextField;
    private javax.swing.JLabel verifyClaimJLabel;
    // End of variables declaration//GEN-END:variables
}
