/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdminRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.InsuranceAgent.InsuranceAgent;
import Business.InsuranceApprover.InsuranceApprover;
import Business.InsuranceInvestigator.InsuranceInvestigator;
import Business.Organization.CustomerOrganization;
import Business.Organization.HospitalAdminOrganization;
import Business.Organization.InsuranceAdminOrganization;
import Business.Organization.InsuranceAgentOrganization;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.InsuranceInvestigatorOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import java.awt.CardLayout;
import java.util.function.Function;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anusha
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeesJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;

    public ManageEmployeesJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (!(organization instanceof CustomerOrganization)) {
                organizationJComboBox.addItem(organization);
            }
        }
    }

    public void populateOrganizationEmpComboBox() {
        organizationEmpJComboBox.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (!(organization instanceof CustomerOrganization)) {
                organizationEmpJComboBox.addItem(organization);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmployeeJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        organisationJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        employeeNameJLabel = new javax.swing.JLabel();
        employeeNameJTextField = new javax.swing.JTextField();
        organizationEmpJComboBox = new javax.swing.JComboBox();
        organisationTypeJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emplyeeJTable = new javax.swing.JTable();
        addEmployeeLabel = new javax.swing.JLabel();
        employeeDirectoryJLabel = new javax.swing.JLabel();

        addEmployeeJButton.setText("Create Employee");
        addEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeJButtonActionPerformed(evt);
            }
        });

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        organisationJLabel.setText("Organization");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        employeeNameJLabel.setText("Name");

        organizationEmpJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationEmpJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBoxActionPerformed(evt);
            }
        });

        organisationTypeJLabel.setText("Organization");

        emplyeeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(emplyeeJTable);

        addEmployeeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addEmployeeLabel.setText("Add Employee");

        employeeDirectoryJLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        employeeDirectoryJLabel.setText("Employee Directory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(organisationJLabel)
                        .addGap(48, 48, 48)
                        .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDirectoryJLabel)
                    .addComponent(addEmployeeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(organisationTypeJLabel)
                            .addComponent(employeeNameJLabel))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmployeeJButton)
                            .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(employeeDirectoryJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organisationJLabel)
                            .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(addEmployeeLabel)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organisationTypeJLabel)
                            .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeNameJLabel)
                            .addComponent(employeeNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(addEmployeeJButton)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeJButtonActionPerformed

        try {
            Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
            String name = employeeNameJTextField.getText();
//                Employee employee = new Employee();
//                employee.setName(name);
            //  employee.setType(organization.getName());

            if (organization instanceof InsuranceAgentOrganization) {
                InsuranceAgent ia = new InsuranceAgent();
                ia.setName(name);
                organization.getPersonDirectory().getPersonList().add(ia);
            } else if (organization instanceof InsuranceApproverOrganization) {
                InsuranceApprover ap = new InsuranceApprover();
                ap.setName(name);
                organization.getPersonDirectory().getPersonList().add(ap);
            } else if (organization instanceof InsuranceInvestigatorOrganization) {
                InsuranceInvestigator ii = new InsuranceInvestigator();
                ii.setName(name);
                organization.getPersonDirectory().getPersonList().add(ii);
            }
            JOptionPane.showMessageDialog(null, "Person added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            employeeNameJTextField.setText("");
            populateOrganizationTable(organization);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_addEmployeeJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed

        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null) {
            populateOrganizationTable(organization);
        }

    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    public void populateOrganizationTable(Organization organization) {
        DefaultTableModel model = (DefaultTableModel) emplyeeJTable.getModel();
        model.setRowCount(0);

        for (Person person : organization.getPersonDirectory().getPersonList()) {
            Object[] row = new Object[1];
            row[0] = person.getName();
            model.addRow(row);
        }
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void organizationEmpJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBoxActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
    }//GEN-LAST:event_organizationEmpJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeJButton;
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel employeeDirectoryJLabel;
    private javax.swing.JLabel employeeNameJLabel;
    private javax.swing.JTextField employeeNameJTextField;
    private javax.swing.JTable emplyeeJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel organisationJLabel;
    private javax.swing.JLabel organisationTypeJLabel;
    private javax.swing.JComboBox organizationEmpJComboBox;
    private javax.swing.JComboBox organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
