/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anusha
 */
public class ManageOrganisationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganisationsJPanel
     */
      JPanel userProcessContainer;
    Enterprise enterprise;
    public ManageOrganisationsJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateOrganizationTypeComboBox();
        populateOrganizationTable();
    }

    public void populateOrganizationTypeComboBox(){
        organizationTypeJComboBox.removeAllItems();
        if(enterprise instanceof InsuranceEnterprise){
            for(Organization.Type type : Organization.Type.values()){
                if((!type.getValue().equals(Organization.Type.InsuranceAdmin.getValue())) && (!type.getValue().equals(Organization.Type.HospitalAdmin.getValue())) ){
                    organizationTypeJComboBox.addItem(type);
                }
            }
        }        
    }
    
        public void populateOrganizationTable(){
        DefaultTableModel model = (DefaultTableModel)organizationJTable.getModel();
        model.setRowCount(0);
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[1];
            row[0] = organization.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        organisationTypeJLabel = new javax.swing.JLabel();
        organizationTypeJComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        addOrganisationJButton = new javax.swing.JButton();

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        organisationTypeJLabel.setText("Organization Type ");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        addOrganisationJButton.setText("Add Organization");
        addOrganisationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganisationJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(organisationTypeJLabel)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addOrganisationJButton)
                            .addComponent(organizationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisationTypeJLabel)
                    .addComponent(organizationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(addOrganisationJButton)
                .addGap(142, 142, 142)
                .addComponent(backJButton)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addOrganisationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganisationJButtonActionPerformed

         try{
            boolean alreadyPresent = false;
            Organization.Type type = (Organization.Type) organizationTypeJComboBox.getSelectedItem();
            if(enterprise.getOrganizationDirectory().getOrganizationList().isEmpty()){
                enterprise.getOrganizationDirectory().createOrganization(type);
                populateOrganizationTable();
            }else{
                for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org.getName().equalsIgnoreCase(type.getValue())){
                        alreadyPresent = true;
                        JOptionPane.showMessageDialog(null, "Organization is already added", "Warning", JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                }
                if(!alreadyPresent){
                        enterprise.getOrganizationDirectory().createOrganization(type);
                        populateOrganizationTable();
                    }
                
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
        
       
    }//GEN-LAST:event_addOrganisationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganisationJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel organisationTypeJLabel;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JComboBox organizationTypeJComboBox;
    // End of variables declaration//GEN-END:variables
}
