/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceApproverRole;

import Business.Enterprise.Enterprise;
import Business.Hospital.VitalSigns;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ApprovalRequest;
import Business.WorkQueue.HospitalWorkRequest;
import Business.WorkQueue.WorkRequest;
import business.SendEmail;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anusha
 */
public class VerifySelectedPolicyJPanel extends javax.swing.JPanel {
    
    ApprovalRequest request1;
    Enterprise enterprise;
    JPanel userProcessContainer;
    HospitalWorkRequest hrequest;

    /**
     * Creates new form VerifySelectedPolicyJPanel
     */

    VerifySelectedPolicyJPanel(JPanel userProcessContainer, Enterprise enterprise, ApprovalRequest request1) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.request1 = request1;
        populateForms();
    }
    
    public void populateForms(){
        customerNameTextField.setText(request1.getCustomerName());
        sumInsuredTextField.setText(request1.getSumInsured());
        premiumAmountJTextField.setText(request1.getPremiumAmt());
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof InsuranceApproverOrganization)
            {
                for(WorkRequest request : org.getWorkQueue().getWorkRequestList())
                {
                    if(request instanceof HospitalWorkRequest)
                    {
                        
                            sBloodPressureJTextField.setText(String.valueOf(((HospitalWorkRequest) request).getSbp()));
                            dBloodPressureJTextField.setText(String.valueOf(((HospitalWorkRequest) request).getDbp()));
                            hdlCholestrolJTextField.setText(String.valueOf(((HospitalWorkRequest) request).getHdlC()));
                            ldlCholestrolTextField.setText(String.valueOf(((HospitalWorkRequest) request).getHdlC()));
                            ;
                        
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sBloodPressureJTextField = new javax.swing.JTextField();
        dBloodPressureJTextField = new javax.swing.JTextField();
        hdlCholestrolJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ldlCholestrolTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        policyDetailsJLabel = new javax.swing.JLabel();
        hositalDetailsJLabel = new javax.swing.JLabel();
        approveJButton = new javax.swing.JButton();
        denyJButton = new javax.swing.JButton();
        sumInsuredJLabel = new javax.swing.JLabel();
        sumInsuredTextField = new javax.swing.JTextField();
        premiumAmountJLabel = new javax.swing.JLabel();
        premiumAmountJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Verify Policies");

        jLabel2.setText("Customer Name:");

        policyDetailsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        policyDetailsJLabel.setText("POLICY DETAILS");

        hositalDetailsJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hositalDetailsJLabel.setText("HOSPITAL DETAILS");

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        denyJButton.setText("Deny");
        denyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyJButtonActionPerformed(evt);
            }
        });

        sumInsuredJLabel.setText("Sum Insured :");

        sumInsuredTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumInsuredTextFieldActionPerformed(evt);
            }
        });

        premiumAmountJLabel.setText("Premium Amount :");

        jLabel4.setText("Systolic Blood Pressure:");

        jLabel5.setText("Diastolic Blood Pressure:");

        jLabel6.setText("HDL Cholestrol:");

        jLabel7.setText("LDL Cholestrol:");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(632, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(592, 592, 592))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jLabel2)
                                                .addGap(42, 42, 42))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(sumInsuredJLabel)
                                                    .addComponent(premiumAmountJLabel))
                                                .addGap(36, 36, 36)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(customerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(sumInsuredTextField)
                                            .addComponent(premiumAmountJTextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(approveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(denyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(policyDetailsJLabel)
                                .addGap(284, 284, 284)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hositalDetailsJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sBloodPressureJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(dBloodPressureJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hdlCholestrolJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ldlCholestrolTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hositalDetailsJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sBloodPressureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dBloodPressureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policyDetailsJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hdlCholestrolJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ldlCholestrolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sumInsuredJLabel)
                            .addComponent(sumInsuredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(premiumAmountJLabel)
                            .addComponent(premiumAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(approveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(denyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sumInsuredTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumInsuredTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumInsuredTextFieldActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        //SendEmail.SendMail(, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY);
        
        request1.setMessage("Approved");
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void denyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyJButtonActionPerformed
        // TODO add your handling code here:
        request1.setMessage("Denied");
    }//GEN-LAST:event_denyJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField dBloodPressureJTextField;
    private javax.swing.JButton denyJButton;
    private javax.swing.JTextField hdlCholestrolJTextField;
    private javax.swing.JLabel hositalDetailsJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField ldlCholestrolTextField;
    private javax.swing.JLabel policyDetailsJLabel;
    private javax.swing.JLabel premiumAmountJLabel;
    private javax.swing.JTextField premiumAmountJTextField;
    private javax.swing.JTextField sBloodPressureJTextField;
    private javax.swing.JLabel sumInsuredJLabel;
    private javax.swing.JTextField sumInsuredTextField;
    // End of variables declaration//GEN-END:variables
}
