/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;


import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.CustomerRole;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anusha
 */
public class NewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form newCustomerJPanel
     */
    public NewCustomerJPanel() {
        
    }
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private Enterprise enterprise;
    
    public NewCustomerJPanel(JPanel userProcessContainer, EcoSystem system, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateNetworkComboBox();
        roleJComboBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpJLabel = new javax.swing.JLabel();
        usernameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        passwordJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        emailJTextField = new javax.swing.JTextField();
        employeeNameJLabel = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox<>();
        emailJLabel = new javax.swing.JLabel();
        custNameJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signUpJLabel.setText("SIGN UP");
        add(signUpJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 92, -1, -1));

        usernameJLabel.setText("Username:");
        add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        passwordJLabel.setText("Password:");
        add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 80, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 136, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, 43));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 136, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 538, -1, -1));

        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 202, -1, -1));

        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 199, 136, -1));

        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 148, -1, -1));

        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 145, 136, -1));
        add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 136, -1));

        employeeNameJLabel.setText("Name:");
        add(employeeNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 52, -1));

        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 140, -1));

        emailJLabel.setText("Email:");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 80, -1));
        add(custNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 136, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//      Component[] componentArray = userProcessContainer.getComponents();
//      Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
            boolean alreadyPresent = false;
            String userName = usernameJTextField.getText();
            String password = String.valueOf(passwordJPasswordField.getPassword());
            String email = emailJTextField.getText();
        
            alreadyPresent = system.checkIfUsernameIsUnique(userName);
            if(!alreadyPresent){
                JOptionPane.showMessageDialog(null, "The User account suggested is already present", "Warning", JOptionPane.WARNING_MESSAGE);
                usernameJTextField.setText("");
                passwordJPasswordField.setText("");
            }else{
                Network net = (Network) networkJComboBox.getSelectedItem();
                Enterprise ep = (Enterprise) enterpriseJComboBox.getSelectedItem();
 
               for (Organization org : ep.getOrganizationDirectory().getOrganizationList()) {
                    if(org instanceof CustomerOrganization){
                           Person person = org.getPersonDirectory().createPerson(custNameJTextField.getText());
                           org.getUserAccountDirectory().createUserAccount(userName, password, email, person, new CustomerRole());
                         JOptionPane.showMessageDialog(null, "Signed up sucessfully");
                         userProcessContainer.remove(this);
                         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                         layout.previous(userProcessContainer);
                         break;   
                       } 
               }
                      
               
            }      
    }//GEN-LAST:event_submitJButtonActionPerformed


    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed

        private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        network.getEnterpriseDirectory().getEnterpriseList().stream().forEach((insenterprise) -> {
            if(insenterprise instanceof InsuranceEnterprise)
            {
                //if enterprise is insurance
                enterpriseJComboBox.addItem(insenterprise);
            } else {
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField custNameJTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel employeeNameJLabel;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JComboBox<String> roleJComboBox;
    private javax.swing.JLabel signUpJLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
