/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAgentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Insurance.Claim;
import Business.Insurance.ClaimDirectory;
import Business.Insurance.PolicyDirectory;
import Business.Network.Network;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.InsuranceInvestigatorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ApprovalRequest;
import Business.WorkQueue.ClaimApprovalRequest;
import Business.WorkQueue.CustomerClaimRequest;
import Business.WorkQueue.CustomerPolicyRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class NewClaimJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewClaimJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    CustomerClaimRequest ccr;
    
    NewClaimJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, UserAccount userAccount, Organization organization,   CustomerClaimRequest ccr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = organization;
        this.ccr = ccr;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewClaimJLabel = new javax.swing.JLabel();
        claimAmountTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sumInsuredTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        createClaimJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewClaimJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NewClaimJLabel.setText("New Claim");
        add(NewClaimJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 11, 141, 41));
        add(claimAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 251, 141, -1));

        jLabel5.setText("Customer Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 178, -1, -1));
        add(custNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 175, 141, -1));

        jLabel7.setText("Sum Insured :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 216, -1, -1));
        add(sumInsuredTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 213, 141, -1));

        jLabel8.setText("Claim Amount :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 254, -1, -1));

        createClaimJButton.setText("Create");
        createClaimJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClaimJButtonActionPerformed(evt);
            }
        });
        add(createClaimJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 408, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createClaimJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClaimJButtonActionPerformed
        // TODO add your handling code here:
        try{
                    if(!custNameTextField.getText().isEmpty()){
                        if(!sumInsuredTextField.getText().isEmpty()){
                            if(!claimAmountTextField.getText().isEmpty()){
                              JOptionPane.showMessageDialog(null,"Claim Created");             
                            }else{
                                JOptionPane.showMessageDialog(null,"Please Enter Claim Amount");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Please Enter Sum Insured");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Please Enter Customer Name");
                    }
               
        
        String custName = custNameTextField.getText();
        String sum = sumInsuredTextField.getText();
        String claimAmount = claimAmountTextField.getText();
        
        ccr.setMessage("Sent for Claim approval");
        
            ccr.setSumInsured(sum);
        ccr.setClaimAmt(claimAmount);
        sendClaimApprovalRequest();
//        
//        Claim claim = claimList.addClaim();
//        claim.setClaimID(claimID);
//        claim.setPolicyID(policy);
//        claim.setCustName(custName);
//        claim.setSumInsured(sum);
//        claim.setClaimAmount(claimAmount);
//        claim.setCustUserName(cust);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_createClaimJButtonActionPerformed

    private void sendClaimApprovalRequest(){
         ClaimApprovalRequest apr = new ClaimApprovalRequest();
    //    cpr.setCustomer(customer);
        apr.setSender(userAccount);
        apr.setMessage("Claim Requested");
        apr.setClaimAmt(ccr.getClaimAmt());
        apr.setSumInsured(ccr.getSumInsured());
        apr.setCustomerName(custNameTextField.getText());
          Organization org = null;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Insurance) {
                    e.getWorkQueue().getWorkRequestList().add(apr);
                }
                for (Organization insApp : e.getOrganizationDirectory().getOrganizationList()) {
                    if (insApp instanceof InsuranceInvestigatorOrganization) {
                        org = insApp;
                        org.getWorkQueue().getWorkRequestList().add(apr);
                        userAccount.getWorkQueue().getWorkRequestList().add(apr);
                    } }}}
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        //        Component[] componentArray = userProcessContainer.getComponents();
        //        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewClaimJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField claimAmountTextField;
    private javax.swing.JButton createClaimJButton;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField sumInsuredTextField;
    // End of variables declaration//GEN-END:variables
}
