/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAgentRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Insurance;
import Business.Enterprise.InsuranceEnterprise;
import Business.Insurance.Policy;
import Business.Insurance.PolicyDirectory;
import Business.Network.Network;
import Business.Organization.InsuranceAgentOrganization;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ApprovalRequest;
import Business.WorkQueue.CustomerPolicyRequest;
import java.awt.CardLayout;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static java.lang.Integer.parseInt;

////
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

/**
 *
 * @author hp
 */
public class NewPolicyJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form NewPolicyJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    CustomerPolicyRequest cpr;

    NewPolicyJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system, UserAccount userAccount, Organization organization,   CustomerPolicyRequest cpr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = organization;
        this.cpr = cpr;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        custNameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sumInsuredJTextField = new javax.swing.JTextField();
        createPolicyJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        amountJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Customer Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 147, -1, -1));
        add(custNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 144, 141, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("New Policy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 11, 141, 41));

        jLabel7.setText("Sum Insured :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 185, -1, -1));
        add(sumInsuredJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 182, 141, -1));

        createPolicyJButton.setText("Create");
        createPolicyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPolicyJButtonActionPerformed(evt);
            }
        });
        add(createPolicyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 360, -1, -1));

        jLabel8.setText("Premium Amount :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 216, -1, -1));
        add(amountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 213, 141, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 406, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createPolicyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPolicyJButtonActionPerformed
        // TODO add your handling code here:
        
        try{
                if(!custNameJTextField.getText().isEmpty()){
                    if(!sumInsuredJTextField.getText().isEmpty()){
                        if(!amountJTextField.getText().isEmpty()){
                            JOptionPane.showMessageDialog(null,"Policy Created");
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Please Enter Premium Amount");
                        }}else{
                        JOptionPane.showMessageDialog(null,"Please Enter Sum Insured");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Please Enter Customer Name");
                }
            

        String custName = custNameJTextField.getText();
        String sumInsured = sumInsuredJTextField.getText();
        String amount = amountJTextField.getText();
        
        
        cpr.setMessage("Sent for policy approval");
        
        cpr.setSumInsured(sumInsured);
        cpr.setPremiumAmt(amount);
        
        sendApprovalRequest();
        
        
     //   Policy policy = policyList.
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_createPolicyJButtonActionPerformed
    private void sendApprovalRequest(){
          ApprovalRequest apr = new ApprovalRequest();
    //    cpr.setCustomer(customer);
        apr.setCustomer(cpr.getCustomer());
        apr.setPolicy(cpr.getPolicy());
        apr.setSumInsured(cpr.getSumInsured());
        apr.setPremiumAmt(cpr.getPremiumAmt());
        apr.setSender(userAccount);
        apr.setMessage("Policy Requested");
        apr.setCustomerName(custNameJTextField.getText());
          Organization org = null;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Insurance) {
                    e.getWorkQueue().getWorkRequestList().add(apr);
                }
                for (Organization insApp : e.getOrganizationDirectory().getOrganizationList()) {
                    if (insApp instanceof InsuranceApproverOrganization) {
                        org = insApp;
                        org.getWorkQueue().getWorkRequestList().add(apr);
                        userAccount.getWorkQueue().getWorkRequestList().add(apr);
                    } }}}
    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createPolicyJButton;
    private javax.swing.JTextField custNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField sumInsuredJTextField;
    // End of variables declaration//GEN-END:variables
}
