/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InsuranceAgentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anusha
 */

public class ViewClaimJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewClaimJPanel
     */
    public ViewClaimJPanel() {
        initComponents();
    }
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;

    ViewClaimJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        claimDetailsLabel = new javax.swing.JLabel();
        claimIDJTextField = new javax.swing.JTextField();
        editJButton = new javax.swing.JButton();
        customerIDJLabel = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        claimAmountJLabel = new javax.swing.JLabel();
        sumInsuredTextField = new javax.swing.JTextField();
        sumInsuredJLabel = new javax.swing.JLabel();
        customerIDJTextField = new javax.swing.JTextField();
        claimAmountJTextField = new javax.swing.JTextField();
        customerNameJLabel = new javax.swing.JLabel();
        claimIDJLabel = new javax.swing.JLabel();
        customerNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        policyIDJLabel1 = new javax.swing.JLabel();
        policyIDJTextField1 = new javax.swing.JTextField();
        StatusJLabel = new javax.swing.JLabel();
        statusJTextField = new javax.swing.JTextField();
        statusJLabel2 = new javax.swing.JLabel();
        fraudStatusJTextField = new javax.swing.JTextField();

        claimDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        claimDetailsLabel.setText(" Claim Details");

        claimIDJTextField.setEditable(false);
        claimIDJTextField.setEnabled(false);

        editJButton.setText("Edit");

        customerIDJLabel.setText("Customer ID :");

        saveJButton.setText("Save");

        claimAmountJLabel.setText("Claim Amount :");

        sumInsuredTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumInsuredTextFieldActionPerformed(evt);
            }
        });

        sumInsuredJLabel.setText("Sum Insured :");

        customerIDJTextField.setEditable(false);
        customerIDJTextField.setEnabled(false);

        customerNameJLabel.setText("Customer Name :");

        claimIDJLabel.setText("Claim ID :");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        policyIDJLabel1.setText("Policy ID :");

        policyIDJTextField1.setEditable(false);
        policyIDJTextField1.setEnabled(false);

        StatusJLabel.setText("Status:");

        statusJTextField.setEditable(false);
        statusJTextField.setEnabled(false);

        statusJLabel2.setText("Genuine/Fraud:");

        fraudStatusJTextField.setEditable(false);
        fraudStatusJTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(claimDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(statusJLabel2)
                                    .addComponent(policyIDJLabel1)
                                    .addComponent(sumInsuredJLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(claimIDJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(customerIDJLabel))
                                    .addComponent(customerNameJLabel)
                                    .addComponent(claimAmountJLabel)
                                    .addComponent(StatusJLabel))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(policyIDJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(editJButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(saveJButton)
                                            .addGap(253, 253, 253))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(claimIDJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(claimAmountJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(customerNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sumInsuredTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(statusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fraudStatusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(claimDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDJLabel))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claimIDJLabel)
                    .addComponent(claimIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policyIDJLabel1)
                    .addComponent(policyIDJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameJLabel)
                    .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumInsuredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumInsuredJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claimAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimAmountJLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusJLabel)
                    .addComponent(statusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusJLabel2)
                    .addComponent(fraudStatusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editJButton)
                    .addComponent(saveJButton))
                .addGap(46, 46, 46)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sumInsuredTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumInsuredTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumInsuredTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StatusJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel claimAmountJLabel;
    private javax.swing.JTextField claimAmountJTextField;
    private javax.swing.JLabel claimDetailsLabel;
    private javax.swing.JLabel claimIDJLabel;
    private javax.swing.JTextField claimIDJTextField;
    private javax.swing.JLabel customerIDJLabel;
    private javax.swing.JTextField customerIDJTextField;
    private javax.swing.JLabel customerNameJLabel;
    private javax.swing.JTextField customerNameJTextField;
    private javax.swing.JButton editJButton;
    private javax.swing.JTextField fraudStatusJTextField;
    private javax.swing.JLabel policyIDJLabel1;
    private javax.swing.JTextField policyIDJTextField1;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel statusJLabel2;
    private javax.swing.JTextField statusJTextField;
    private javax.swing.JLabel sumInsuredJLabel;
    private javax.swing.JTextField sumInsuredTextField;
    // End of variables declaration//GEN-END:variables
}
