/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Patient;
import Business.Hospital.PatientDirectory;
import Business.Hospital.VitalSignHistory;
import Business.Hospital.VitalSigns;
import Business.Network.Network;
import Business.Organization.HospitalAdminOrganization;
import Business.Organization.InsuranceAdminOrganization;
import Business.Organization.InsuranceApproverOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.ApprovalRequest;
import Business.WorkQueue.HospitalWorkRequest;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class AddVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVitalSignsJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    private int sysBp;
    private int diasBp;
    private int hdlCholestrol;
    private int ldlCholestrol;
    private boolean diabetic;
    private boolean smoking;
    private String patient;
    ApprovalRequest request;
    HospitalWorkRequest hrequest;
    EcoSystem ecoSystem;

    AddVitalSignsJPanel(JPanel userProcessContainer, Enterprise enterprise, ApprovalRequest request1, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.request = request1;
        patientIdTextField.setText((request.getCustomerName()));
        this.ecoSystem = ecoSystem;
                
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addVitalSignJButton = new javax.swing.JButton();
        patientIdJLabel = new javax.swing.JLabel();
        patientIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        systolicBPTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diastolicBPTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hdlCholestrolTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ldlCholestrolTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        diabeticTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        smokingTextField = new javax.swing.JTextField();
        registerJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Add Vital Signs");

        addVitalSignJButton.setText("Add");
        addVitalSignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalSignJButtonActionPerformed(evt);
            }
        });

        patientIdJLabel.setText("Patient ID: ");

        jLabel2.setText("Systolic Blood Pressure:");

        systolicBPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systolicBPTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Diastolic Blood Pressure:");

        jLabel4.setText("HDL Cholestrol:");

        jLabel5.setText("LDL Cholestrol:");

        jLabel6.setText("Diabetic:");

        jLabel7.setText("Smoking:");

        registerJButton.setText("Register Vital Signs");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(patientIdJLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diabeticTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smokingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldlCholestrolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hdlCholestrolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diastolicBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systolicBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(361, 361, 361)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(182, 182, 182)
                            .addComponent(addVitalSignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(registerJButton))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIdJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(systolicBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diastolicBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hdlCholestrolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ldlCholestrolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(diabeticTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(smokingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVitalSignJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVitalSignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalSignJButtonActionPerformed
        // TODO add your handling code here:
        systolicBPTextField.setEditable(false);
        diastolicBPTextField.setEditable(false);
        hdlCholestrolTextField.setEditable(false);
        ldlCholestrolTextField.setEditable(false);
        diabeticTextField.setEditable(false);
        smokingTextField.setEditable(false);
        patientIdTextField.setEditable(false);
        
        if(!patientIdTextField.getText().isEmpty()){
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter Patient ID");
        }
        
        
        sysBp = 100 + (int)(Math.random()*(100-70));
        systolicBPTextField.setText(String.valueOf(sysBp));
        diasBp = 100 + (int)(Math.random() * (180-120));
        diastolicBPTextField.setText(String.valueOf(diasBp));
        hdlCholestrol = 10 + (int)(Math.random() * (25-10));
        hdlCholestrolTextField.setText(String.valueOf(hdlCholestrol));
        ldlCholestrol = 10 + (int)(Math.random() * (25-10));
        ldlCholestrolTextField.setText(String.valueOf(ldlCholestrol));
        diabetic = new Random().nextBoolean();
        diabeticTextField.setText(String.valueOf(diabetic));
        smoking = new Random().nextBoolean();
        smokingTextField.setText(String.valueOf(smoking));
        addVitalSignJButton.setEnabled(false);
          
    }//GEN-LAST:event_addVitalSignJButtonActionPerformed

    private void systolicBPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systolicBPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_systolicBPTextFieldActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient();
        patient.setPatientId(patientIdTextField.getText());

        //patient = patientIdTextField.getText();
        

        VitalSigns vs = patient.getVitalSignHistory().addVitalSigns();
        vs.setSystolicBP(sysBp);
        vs.setDiastolicBP(diasBp);
        vs.setHdlCholestrol(hdlCholestrol);
        vs.setLdlCholestrol(ldlCholestrol);
        vs.setDiabetic(diabetic);
        vs.setSmoking(smoking);

        JOptionPane.showMessageDialog(null,"Vital Signs Registered Successfully");
        
        registerJButton.setEnabled(false);
        
        hrequest = new HospitalWorkRequest();
        hrequest.setPatient(patient);
        hrequest.setVitalSignHistory(patient.getVitalSignHistory());
        
        hrequest.setSbp(sysBp);
        hrequest.setDbp(diasBp);
        hrequest.setHdlC(hdlCholestrol);
        hrequest.setLdlC(ldlCholestrol);
        
         for (Network n : ecoSystem.getNetworkList())
         {
             for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList())
             {
                 for(Organization organization: e.getOrganizationDirectory().getOrganizationList())
                 {
                     if (organization instanceof InsuranceApproverOrganization) {
                        
                        organization.getWorkQueue().getWorkRequestList().add(hrequest);
                        
                    } 
                 }
             }
         }     

    }//GEN-LAST:event_registerJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVitalSignJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField diabeticTextField;
    private javax.swing.JTextField diastolicBPTextField;
    private javax.swing.JTextField hdlCholestrolTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField ldlCholestrolTextField;
    private javax.swing.JLabel patientIdJLabel;
    private javax.swing.JTextField patientIdTextField;
    private javax.swing.JButton registerJButton;
    private javax.swing.JTextField smokingTextField;
    private javax.swing.JTextField systolicBPTextField;
    // End of variables declaration//GEN-END:variables
}
